#!/usr/bin/env python3
"""Audit Ariadne HTML reports for coverage/body consistency."""

from __future__ import annotations

import argparse
import html as html_lib
import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path


FORBIDDEN_WORKBENCH_SECTIONS = {
    "executive-diagnosis",
    "issue-index",
    "claim-evidence-audit",
    "deep-reading-notes",
    "submission-readiness",
    "local-comments",
    "revision-plan",
}
REQUIRED_SECTIONS_BY_KIND = {
    "pdf-overlay": {"paper-reader", "bbox-diagnostics", "coverage-receipt"},
    "issue-report-only": {"issue-report", "coverage-receipt"},
}

NUMERIC_CONTEXT_RE = re.compile(
    r"(Safety Score|Avg|Average|Mean|均值|平均|delta|reported|computed|复算|表中写|偏差|隐藏小数|需核对|需要核对|需复查|建议复查)",
    re.IGNORECASE,
)
VAGUE_NUMERIC_RE = re.compile(r"(有偏差|需核对|需要核对|需复查|建议复查|可能来自隐藏小数|hidden decimals?)", re.IGNORECASE)
NUMERIC_VALUE_RE = re.compile(r"[-+]?\d+(?:\.\d+)?")
CONCRETE_NUMERIC_CUE_RE = re.compile(
    r"(reported|computed|visible_computed|visible computed|visible arithmetic mean|复算|表中写|不是|delta|差值)",
    re.IGNORECASE,
)
NUMERIC_TEXT_TAGS = {"p", "li", "td", "th", "article", "section"}

LEGACY_SPLIT_NOTE_SECTIONS = {
    "top-priorities",
    "section-review",
    "paragraph-surgery",
    "margin-notes",
    "keep-notes",
}
FORBIDDEN_WORKBENCH_SECTIONS.update(LEGACY_SPLIT_NOTE_SECTIONS)
FORBIDDEN_PAPER_READER_CARD_LABELS = {"位置", "原句/片段", "证据/验证"}
MECHANICAL_CARD_PROVENANCE_RE = re.compile(
    r"(data-sentence-id|data-paragraph-id|source-derived paper-reader|generated by render_paper_html\.py|"
    r"sentence span generated|paragraph id generated|heading id generated|section-paragraph-sentence)",
    re.IGNORECASE,
)
MEANINGFUL_CARD_EVIDENCE_RE = re.compile(
    r"(table|figure|caption|pdf|page|computed|recomputed|reported|visible|reference|citation|bib|checklist|"
    r"source line|human|audit|表|图|页|复算|差值|引用|文献|清单|源码|人工|审计)",
    re.IGNORECASE,
)
HASH_RE = re.compile(r"^(sha1|sha256):([0-9a-fA-F]{8,})$")
ATTR_RE = re.compile(r"([A-Za-z_:][-A-Za-z0-9_:.]*)=(['\"])(.*?)\2", re.DOTALL)
PDFJS_OVERLAY_RE = re.compile(
    r"<script\b[^>]*\bid=(['\"])pdf-overlay-data\1[^>]*>(.*?)</script>",
    re.IGNORECASE | re.DOTALL,
)


def compact_text(value: object) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def parse_declared_hash(value: str) -> tuple[str, str] | None:
    match = HASH_RE.fullmatch(value.strip())
    if not match:
        return None
    return match.group(1), match.group(2).lower()


def audit_overlay_card_copy(parser: "AriadneHTMLParser") -> list[str]:
    errors: list[str] = []
    for card in parser.overlay_card_texts:
        card_id = card.get("id") or "<unknown annotation card>"
        labels = card.get("labels", [])
        for label in labels if isinstance(labels, list) else []:
            label = compact_text(label).rstrip("：:")
            if label in FORBIDDEN_PAPER_READER_CARD_LABELS:
                errors.append(
                    f"PDF overlay annotation card `{card_id}` must not show visible `{label}`; "
                    "the active paper anchor already supplies location/source text"
                )
        text = compact_text(card.get("text"))
        if MECHANICAL_CARD_PROVENANCE_RE.search(text):
            errors.append(f"PDF overlay annotation card `{card_id}` exposes mechanical renderer provenance")
        has_evidence_label = any(compact_text(label).rstrip("：:") == "核查依据" for label in labels if isinstance(labels, list))
        if has_evidence_label and not MEANINGFUL_CARD_EVIDENCE_RE.search(text):
            errors.append(
                f"PDF overlay annotation card `{card_id}` shows `核查依据` without concrete manuscript-level evidence"
            )
    return errors


def parse_attrs(fragment: str) -> dict[str, str]:
    return {name: html_lib.unescape(value) for name, _, value in ATTR_RE.findall(fragment)}


def load_pdfjs_overlay_fragments(text: str) -> list[str]:
    match = PDFJS_OVERLAY_RE.search(text)
    if not match:
        return []
    raw = html_lib.unescape(match.group(2))
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return []
    fragments: list[str] = []
    if isinstance(payload, dict):
        for value in payload.values():
            if isinstance(value, list):
                fragments.extend(str(item) for item in value)
    return fragments


def add_pdfjs_overlay_controls(parser: "AriadneHTMLParser", fragments: list[str]) -> None:
    for fragment in fragments:
        attrs = parse_attrs(fragment)
        class_names = attrs.get("class", "").split()
        sentence_id = attrs.get("data-sentence-id", "")
        if "paper-sentence" in class_names and sentence_id:
            parser.paper_sentence_ids.add(sentence_id)
            parser.issue_sentences.append(
                {
                    "sentence_id": sentence_id,
                    "severity": attrs.get("data-severity", ""),
                    "issue_type": attrs.get("data-issue-type", ""),
                    "issue_ids": attrs.get("data-issue-ids", ""),
                    "data_has_issue": attrs.get("data-has-issue", ""),
                    "aria_describedby": attrs.get("aria-describedby", ""),
                    "tag": "button",
                }
            )
            for ref in re.findall(r"F\d+[A-Za-z]?", attrs.get("data-issue-ids", "")):
                parser.issue_sentence_refs.append((ref, sentence_id))
        paragraph_id = attrs.get("data-paragraph-id", "")
        section_id = attrs.get("data-section-id", "")
        paper_id = attrs.get("data-paper-id", "")
        if paragraph_id:
            parser.paper_paragraph_ids.add(paragraph_id)
        if section_id:
            parser.paper_section_ids.add(section_id)
        if paper_id:
            parser.paper_overview_ids.add(paper_id)
        for level, target_id, marker_class in (
            ("paragraph", paragraph_id, "has-paragraph-annotation"),
            ("section", section_id, "has-section-annotation"),
            ("paper", paper_id if "paper" in class_names else "", "has-paper-annotation"),
        ):
            if target_id and marker_class in class_names:
                parser.issue_anchors.append(
                    {
                        "level": level,
                        "target": target_id,
                        "severity": attrs.get("data-severity", ""),
                        "issue_type": attrs.get("data-issue-type", ""),
                        "issue_ids": attrs.get("data-issue-ids", ""),
                        "data_has_issue": attrs.get("data-has-issue", ""),
                    }
                )
                for ref in re.findall(r"F\d+[A-Za-z]?", attrs.get("data-issue-ids", "")):
                    parser.issue_sentence_refs.append((ref, target_id))


class AriadneHTMLParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.ids: set[str] = set()
        self.report_kind = ""
        self.href_anchors: set[str] = set()
        self.section_stack: list[str] = []
        self.counts = {
            "pdf_pages": 0,
            "pdfjs_viewers": 0,
            "severity_items": 0,
        }
        self.text_stack: list[tuple[str, list[str]]] = []
        self.numeric_texts: list[str] = []
        self.defined_finding_ids: set[str] = set()
        self.linked_finding_refs: list[tuple[str, str]] = []
        self.raw_schema_key_texts: list[str] = []
        self.tables: list[dict[str, object]] = []
        self.table_stack: list[dict[str, object]] = []
        self.section_text_stack: list[tuple[str, list[str]]] = []
        self.section_texts: dict[str, str] = {}
        self.issue_item_stack: list[dict[str, str | list[str]]] = []
        self.issue_items: list[dict[str, str]] = []
        self.paper_sentence_ids: set[str] = set()
        self.paper_paragraph_ids: set[str] = set()
        self.paper_section_ids: set[str] = set()
        self.paper_overview_ids: set[str] = set()
        self.issue_sentences: list[dict[str, str]] = []
        self.issue_anchors: list[dict[str, str]] = []
        self.annotation_targets: set[tuple[str, str]] = set()
        self.annotation_cards: list[dict[str, str]] = []
        self.unanchored_annotation_cards: list[dict[str, str]] = []
        self.annotation_issue_refs: list[tuple[str, str]] = []
        self.issue_sentence_refs: list[tuple[str, str]] = []
        self.paper_panes: list[dict[str, str]] = []
        self.overlay_card_stack: list[dict[str, object]] = []
        self.overlay_card_texts: list[dict[str, object]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr = {key: value or "" for key, value in attrs}
        element_id = attr.get("id")
        class_names = attr.get("class", "").split()
        if "review-report" in class_names and attr.get("data-report-kind"):
            self.report_kind = attr.get("data-report-kind", "")
        if element_id:
            self.ids.add(element_id)
        href = attr.get("href", "")
        if href.startswith("#") and len(href) > 1:
            self.href_anchors.add(href[1:])

        if tag == "section":
            self.section_stack.append(element_id or "")
            self.section_text_stack.append((element_id or "", []))
            if "pdf-anchor" in attr.get("class", "").split():
                self.counts["pdf_pages"] += 1

        if "paper-reader" in self.section_stack:
            if "annotation-card" in class_names:
                self.overlay_card_stack.append(
                    {
                        "tag": tag,
                        "id": element_id or attr.get("data-issue-ids") or "<unknown annotation card>",
                        "text_parts": [],
                        "label_stack": [],
                        "labels": [],
                    }
                )
            if self.overlay_card_stack and tag in {"dt", "strong", "b", "th"}:
                label_stack = self.overlay_card_stack[-1].get("label_stack")
                if isinstance(label_stack, list):
                    label_stack.append([])
            if "paper-pane" in class_names:
                self.paper_panes.append(
                    {
                        "paper_view": attr.get("data-paper-view", ""),
                        "source": attr.get("data-paper-html-source", ""),
                        "fidelity": attr.get("data-source-fidelity", ""),
                        "artifact": attr.get("data-source-artifact", ""),
                        "hash": attr.get("data-source-hash", ""),
                        "sentence_id_scheme": attr.get("data-sentence-id-scheme", ""),
                        "annotation_mode": attr.get("data-annotation-mode", ""),
                        "visible_scope": attr.get("data-visible-scope", ""),
                    }
                )
            if element_id == "pdfjs-viewer":
                self.counts["pdfjs_viewers"] += 1
            sentence_id = attr.get("data-sentence-id", "")
            is_paper_sentence = "paper-sentence" in class_names
            is_issue_sentence = (
                is_paper_sentence
                and (
                    "has-annotation" in class_names
                    or attr.get("data-has-issue") == "true"
                    or bool(attr.get("data-issue-ids"))
                )
            )
            if is_paper_sentence:
                if sentence_id:
                    self.paper_sentence_ids.add(sentence_id)
                if is_issue_sentence:
                    issue_ids = attr.get("data-issue-ids", "")
                    self.issue_sentences.append(
                        {
                            "sentence_id": sentence_id,
                            "severity": attr.get("data-severity", ""),
                            "issue_type": attr.get("data-issue-type", ""),
                            "issue_ids": issue_ids,
                            "data_has_issue": attr.get("data-has-issue", ""),
                            "aria_describedby": attr.get("aria-describedby", ""),
                            "tag": tag,
                        }
                    )
                    for ref in re.findall(r"F\d+[A-Za-z]?", issue_ids):
                        self.issue_sentence_refs.append((ref, sentence_id or "<missing sentence id>"))
            paragraph_id = attr.get("data-paragraph-id", "")
            section_anchor_id = attr.get("data-section-id", "")
            if paragraph_id:
                self.paper_paragraph_ids.add(paragraph_id)
            if section_anchor_id:
                self.paper_section_ids.add(section_anchor_id)
            elif element_id:
                self.paper_section_ids.add(element_id)
            if element_id == "paper-overview-annotations":
                self.paper_overview_ids.add("paper")
            paper_button_id = attr.get("data-paper-id", "")
            if paper_button_id and "annotation-bubble" in class_names and "paper" in class_names:
                self.paper_overview_ids.add(paper_button_id)
            for level, target_id, marker_class in (
                ("paragraph", paragraph_id, "has-paragraph-annotation"),
                ("section", section_anchor_id or element_id or "", "has-section-annotation"),
                ("paper", paper_button_id if "annotation-bubble" in class_names and "paper" in class_names else "", "has-paper-annotation"),
            ):
                if target_id and marker_class in class_names:
                    issue_ids = attr.get("data-issue-ids", "")
                    self.issue_anchors.append(
                        {
                            "level": level,
                            "target": target_id,
                            "severity": attr.get("data-severity", ""),
                            "issue_type": attr.get("data-issue-type", ""),
                            "issue_ids": issue_ids,
                            "data_has_issue": attr.get("data-has-issue", ""),
                        }
                    )
                    for ref in re.findall(r"F\d+[A-Za-z]?", issue_ids):
                        self.issue_sentence_refs.append((ref, target_id))
            is_annotation_card = "annotation-card" in class_names
            is_unanchored_annotation = is_annotation_card and attr.get("data-unanchored") == "true"
            target_sentence = attr.get("data-target-sentence", "")
            target_level = attr.get("data-target-level", "sentence" if target_sentence else "")
            target_paragraph = attr.get("data-target-paragraph", "")
            target_section = attr.get("data-target-section", "")
            target_paper = attr.get("data-target-paper", "")
            if is_unanchored_annotation:
                issue_ids = attr.get("data-issue-ids", "")
                self.unanchored_annotation_cards.append(
                    {
                        "target_level": target_level,
                        "target_sentence": target_sentence,
                        "target_paragraph": target_paragraph,
                        "target_section": target_section,
                        "target_paper": target_paper,
                        "severity": attr.get("data-severity", ""),
                        "issue_type": attr.get("data-issue-type", ""),
                        "issue_ids": issue_ids,
                    }
                )
            target_by_level = {
                "sentence": target_sentence,
                "paragraph": target_paragraph,
                "section": target_section,
                "paper": target_paper,
            }
            target_value = target_by_level.get(target_level, "")
            if target_value:
                issue_ids = attr.get("data-issue-ids", "")
                self.annotation_targets.add((target_level, target_value))
                self.annotation_cards.append(
                    {
                        "target_level": target_level,
                        "target_sentence": target_sentence,
                        "target_paragraph": target_paragraph,
                        "target_section": target_section,
                        "target_paper": target_paper,
                        "severity": attr.get("data-severity", ""),
                        "issue_type": attr.get("data-issue-type", ""),
                        "issue_ids": issue_ids,
                    }
                )
                for ref in re.findall(r"F\d+[A-Za-z]?", issue_ids):
                    self.annotation_issue_refs.append((ref, target_value))

        if "data-severity" in attr:
            self.counts["severity_items"] += 1
            if attr.get("data-issue-type"):
                self.issue_item_stack.append(
                    {
                        "severity": attr.get("data-severity", ""),
                        "issue_type": attr.get("data-issue-type", ""),
                        "tag": tag,
                        "text_parts": [],
                    }
                )
        if tag == "table":
            self.table_stack.append(
                {
                    "has_caption": False,
                    "header_without_scope": 0,
                    "id": element_id or "",
                    "in_paper_pane": "paper-reader" in self.section_stack,
                }
            )
        elif tag == "caption" and self.table_stack:
            self.table_stack[-1]["has_caption"] = True
        elif tag == "th" and self.table_stack:
            if "scope" not in attr:
                self.table_stack[-1]["header_without_scope"] = int(self.table_stack[-1]["header_without_scope"]) + 1
        if element_id and re.fullmatch(r"F\d+[A-Za-z]?", element_id):
            self.defined_finding_ids.add(element_id)
        if tag == "a":
            text_ref = attr.get("href", "")
            if text_ref.startswith("#") and re.fullmatch(r"#F\d+[A-Za-z]?", text_ref):
                self.linked_finding_refs.append((text_ref[1:], text_ref))
        if tag in NUMERIC_TEXT_TAGS:
            self.text_stack.append((tag, []))

    def handle_endtag(self, tag: str) -> None:
        if self.overlay_card_stack and tag in {"dt", "strong", "b", "th"}:
            label_stack = self.overlay_card_stack[-1].get("label_stack")
            labels = self.overlay_card_stack[-1].get("labels")
            if isinstance(label_stack, list) and label_stack:
                parts = label_stack.pop()
                if isinstance(parts, list) and isinstance(labels, list):
                    labels.append(compact_text("".join(str(part) for part in parts)))
        if tag in NUMERIC_TEXT_TAGS and self.text_stack and self.text_stack[-1][0] == tag:
            _, parts = self.text_stack.pop()
            text = "".join(parts).strip()
            if NUMERIC_CONTEXT_RE.search(text):
                self.numeric_texts.append(re.sub(r"\s+", " ", text))
            if re.search(r"\b(reported_value|visible_computed_value|aggregation_caveat)\b", text):
                self.raw_schema_key_texts.append(re.sub(r"\s+", " ", text))
            if self.text_stack and text:
                self.text_stack[-1][1].append(" " + text)
        if tag == "section" and self.section_stack and self.section_stack[-1] == (self.section_text_stack[-1][0] if self.section_text_stack else ""):
            section_id, parts = self.section_text_stack.pop() if self.section_text_stack else ("", [])
            if section_id:
                section_text = re.sub(r"\s+", " ", "".join(parts)).strip()
                self.section_texts[section_id] = section_text
            if self.section_text_stack and parts:
                self.section_text_stack[-1][1].append(" ".join(parts))
            self.section_stack.pop()
        if tag == "table" and self.table_stack:
            self.tables.append(self.table_stack.pop())
        if self.issue_item_stack and tag == self.issue_item_stack[-1].get("tag"):
            item = self.issue_item_stack.pop()
            parts = item.get("text_parts", [])
            text = re.sub(r"\s+", " ", "".join(parts if isinstance(parts, list) else [])).strip()
            self.issue_items.append(
                {
                    "severity": str(item.get("severity", "")),
                    "issue_type": str(item.get("issue_type", "")),
                    "text": text,
                }
            )
        if self.overlay_card_stack and tag == self.overlay_card_stack[-1].get("tag"):
            card = self.overlay_card_stack.pop()
            parts = card.get("text_parts", [])
            text_parts = parts if isinstance(parts, list) else []
            text = compact_text("".join(str(part) for part in text_parts))
            labels = card.get("labels", [])
            self.overlay_card_texts.append(
                {
                    "id": str(card.get("id") or "<unknown annotation card>"),
                    "text": text,
                    "labels": labels if isinstance(labels, list) else [],
                }
            )

    def handle_data(self, data: str) -> None:
        if self.text_stack:
            self.text_stack[-1][1].append(data)
        if self.section_text_stack:
            self.section_text_stack[-1][1].append(data)
        if self.overlay_card_stack:
            card = self.overlay_card_stack[-1]
            parts = card.get("text_parts")
            if isinstance(parts, list):
                parts.append(data)
            label_stack = card.get("label_stack")
            if isinstance(label_stack, list) and label_stack:
                label_parts = label_stack[-1]
                if isinstance(label_parts, list):
                    label_parts.append(data)
        for item in self.issue_item_stack:
            parts = item.get("text_parts")
            if isinstance(parts, list):
                parts.append(data)


def audit(path: Path) -> tuple[list[str], list[str]]:
    text = path.read_text(encoding="utf-8")
    parser = AriadneHTMLParser()
    parser.feed(text)
    add_pdfjs_overlay_controls(parser, load_pdfjs_overlay_fragments(text))

    errors: list[str] = []
    warnings: list[str] = []
    report_kind = parser.report_kind
    is_current_report = report_kind in REQUIRED_SECTIONS_BY_KIND
    is_pdf_overlay = report_kind == "pdf-overlay"
    if not is_current_report:
        errors.append("unsupported or missing data-report-kind; expected `pdf-overlay` or `issue-report-only`")
    required_sections = REQUIRED_SECTIONS_BY_KIND.get(report_kind, set())
    missing_sections = sorted(required_sections - parser.ids)
    for section_id in missing_sections:
        errors.append(f"missing required section #{section_id}")

    if is_current_report:
        forbidden_workbench = sorted(FORBIDDEN_WORKBENCH_SECTIONS & parser.ids)
        if forbidden_workbench:
            errors.append(
                "current Ariadne reports must not render legacy workbench sections: "
                + ", ".join(f"#{section_id}" for section_id in forbidden_workbench)
            )
    if is_pdf_overlay and parser.counts["pdf_pages"] == 0 and parser.counts["pdfjs_viewers"] == 0:
        errors.append("pdf-overlay report has no PDF.js viewer or PDF page anchors")

    if "paper-reader" in parser.ids:
        if "annotation-panel" not in parser.ids:
            errors.append("#paper-reader is missing #annotation-panel")
        if not parser.paper_panes:
            errors.append("#paper-reader is missing a `.paper-pane` with source provenance metadata")
        for idx, pane in enumerate(parser.paper_panes, 1):
            paper_view = pane.get("paper_view", "")
            source = pane.get("source", "")
            fidelity = pane.get("fidelity", "")
            prefix = f"#paper-reader .paper-pane #{idx}"
            if paper_view != "pdfjs-overlay":
                errors.append(f"{prefix} in pdf-overlay report must set data-paper-view=\"pdfjs-overlay\"")
            if source or fidelity:
                errors.append(f"{prefix} in pdf-overlay report must not declare data-paper-html-source/data-source-fidelity")
            for field, attr_name in (
                ("artifact", "data-source-artifact"),
                ("hash", "data-source-hash"),
                ("sentence_id_scheme", "data-sentence-id-scheme"),
                ("annotation_mode", "data-annotation-mode"),
            ):
                if not pane.get(field):
                    errors.append(f"{prefix} is missing `{attr_name}`")
            if pane.get("annotation_mode") and pane.get("annotation_mode") != "pdfjs-overlay":
                errors.append(f"{prefix} must use data-annotation-mode=\"pdfjs-overlay\"")
            if pane.get("hash") and parse_declared_hash(pane["hash"]) is None:
                errors.append(f"{prefix} data-source-hash must look like sha1:<hex> or sha256:<hex>")
        if parser.counts["pdfjs_viewers"] == 0 and not parser.issue_sentences and not parser.issue_anchors:
            errors.append("#paper-reader has no annotated issue anchors (`.paper-sentence.has-annotation`, paragraph/section bubble, or paper overview)")
        if not parser.annotation_cards:
            errors.append("#paper-reader has no annotation cards (`data-target-*`)")
        for item in parser.issue_sentences:
            sentence_id = item.get("sentence_id", "")
            if not sentence_id:
                errors.append("annotated paper sentence is missing `data-sentence-id`")
                continue
            if item.get("data_has_issue") != "true":
                errors.append(f"annotated paper sentence `{sentence_id}` must set data-has-issue=\"true\"")
            for field, attr_name in (
                ("severity", "data-severity"),
                ("issue_type", "data-issue-type"),
                ("issue_ids", "data-issue-ids"),
            ):
                if not item.get(field):
                    errors.append(f"annotated paper sentence `{sentence_id}` is missing `{attr_name}`")
            if ("sentence", sentence_id) not in parser.annotation_targets:
                errors.append(f"annotated paper sentence `{sentence_id}` has no matching annotation card")
        for item in parser.issue_anchors:
            level = item.get("level", "")
            target = item.get("target", "")
            if not target:
                errors.append(f"annotated {level} anchor is missing a target id")
                continue
            if item.get("data_has_issue") != "true":
                errors.append(f"annotated {level} anchor `{target}` must set data-has-issue=\"true\"")
            for field, attr_name in (
                ("severity", "data-severity"),
                ("issue_type", "data-issue-type"),
                ("issue_ids", "data-issue-ids"),
            ):
                if not item.get(field):
                    errors.append(f"annotated {level} anchor `{target}` is missing `{attr_name}`")
            if (level, target) not in parser.annotation_targets:
                errors.append(f"annotated {level} anchor `{target}` has no matching annotation card")
        for item in parser.annotation_cards:
            level = item.get("target_level", "sentence")
            target = (
                item.get("target_sentence", "")
                or item.get("target_paragraph", "")
                or item.get("target_section", "")
                or item.get("target_paper", "")
            )
            if parser.counts["pdfjs_viewers"] == 0:
                if level == "sentence" and target and target not in parser.paper_sentence_ids:
                    errors.append(f"annotation card targets unknown paper sentence `{target}`")
                if level == "paragraph" and target and target not in parser.paper_paragraph_ids:
                    errors.append(f"annotation card targets unknown paper paragraph `{target}`")
                if level == "section" and target and target not in parser.paper_section_ids:
                    errors.append(f"annotation card targets unknown paper section `{target}`")
                if level == "paper" and target and target not in parser.paper_overview_ids:
                    errors.append(f"annotation card targets missing paper overview `{target}`")
            for field, attr_name in (
                ("severity", "data-severity"),
                ("issue_type", "data-issue-type"),
                ("issue_ids", "data-issue-ids"),
            ):
                if not item.get(field):
                    errors.append(f"annotation card for `{target}` is missing `{attr_name}`")
        for item in parser.unanchored_annotation_cards:
            for key in ("target_sentence", "target_paragraph", "target_section", "target_paper"):
                target = item.get(key, "")
                if target:
                    errors.append(f"unanchored annotation card must not set {key.replace('_', '-')} `{target}`")
            for field, attr_name in (
                ("severity", "data-severity"),
                ("issue_type", "data-issue-type"),
                ("issue_ids", "data-issue-ids"),
            ):
                if not item.get(field):
                    errors.append(f"unanchored annotation card is missing `{attr_name}`")
        errors.extend(audit_overlay_card_copy(parser))

    if parser.section_stack or parser.issue_item_stack or parser.text_stack or parser.table_stack:
        errors.append("HTML appears structurally incomplete or misnested; parser stacks were not fully closed")

    for anchor in sorted(parser.href_anchors):
        if anchor not in parser.ids:
            errors.append(f"nav/link target #{anchor} has no matching element id")

    if "Coverage consistency" not in text and "coverage consistency" not in text:
        warnings.append("coverage receipt does not mention Coverage consistency gate")
    if "pending in" in text and "Pending in" not in text:
        warnings.append("pending units are mentioned outside the standard Pending in receipt column")
    for numeric_text in parser.numeric_texts:
        if not VAGUE_NUMERIC_RE.search(numeric_text):
            continue
        numbers = NUMERIC_VALUE_RE.findall(numeric_text)
        has_concrete_cue = bool(CONCRETE_NUMERIC_CUE_RE.search(numeric_text))
        if len(numbers) < 2 or not has_concrete_cue:
            preview = numeric_text[:240]
            errors.append(
                "vague numeric language without concrete reported/computed/delta values: "
                f"{preview!r}"
            )

    for raw_text in parser.raw_schema_key_texts:
        preview = raw_text[:240]
        errors.append(
            "Chinese-facing HTML body renders raw numerical schema keys; use 表中数值 / 可见复算值 / 差值 / 口径说明: "
            f"{preview!r}"
        )

    for ref, source in parser.linked_finding_refs:
        if ref not in parser.defined_finding_ids:
            errors.append(f"linked finding `{ref}` has no matching finding/id anchor")
    if is_pdf_overlay:
        for ref, source in parser.issue_sentence_refs:
            if ref not in parser.defined_finding_ids:
                errors.append(f"paper sentence `{source}` references finding `{ref}` with no matching finding/id anchor")
        for ref, target in parser.annotation_issue_refs:
            if ref not in parser.defined_finding_ids:
                errors.append(f"annotation card for `{target}` references finding `{ref}` with no matching finding/id anchor")

    for table in parser.tables:
        if table.get("in_paper_pane"):
            continue
        if not table.get("has_caption"):
            errors.append("table is missing <caption>")
        if int(table.get("header_without_scope", 0)) > 0:
            errors.append("table has <th> without scope attribute")

    return errors, warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("html", type=Path)
    args = parser.parse_args(argv)

    errors, warnings = audit(args.html)
    for warning in warnings:
        print(f"WARNING: {warning}")
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    if errors:
        return 1
    print("Ariadne HTML report audit passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
