#!/usr/bin/env python3
"""Audit Ariadne HTML reports for coverage/body consistency."""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

try:
    from bs4 import BeautifulSoup
except ModuleNotFoundError:  # pragma: no cover - exercised when optional deps are absent.
    BeautifulSoup = None


PAPER_READER_ONLY_SECTIONS = {
    "paper-reader",
    "coverage-receipt",
}
PAPER_READER_GLOBAL_SECTIONS = {
    "paper-reader",
    "global-findings",
    "coverage-receipt",
}
LEGACY_WORKBENCH_SECTIONS = {
    "paper-reader",
    "executive-diagnosis",
    "issue-index",
    "claim-evidence-audit",
    "deep-reading-notes",
    "submission-readiness",
    "local-comments",
    "revision-plan",
    "coverage-receipt",
}
REQUIRED_SECTIONS_BY_KIND = {
    "paper-reader-only": PAPER_READER_ONLY_SECTIONS,
    "paper-reader-with-global-findings": PAPER_READER_GLOBAL_SECTIONS,
}

NUMERIC_CONTEXT_RE = re.compile(
    r"(Safety Score|Avg|Average|Mean|均值|平均|delta|reported|computed|复算|表中写|偏差|隐藏小数|需核对|需要核对|需复查|建议复查)",
    re.IGNORECASE,
)
VAGUE_NUMERIC_RE = re.compile(r"(有偏差|需核对|需要核对|需复查|建议复查|可能来自隐藏小数|hidden decimals?)", re.IGNORECASE)
NUMERIC_VALUE_RE = re.compile(r"[-+]?\d+(?:\.\d+)?")
CONCRETE_NUMERIC_CUE_RE = re.compile(
    r"(reported|computed|visible_computed|visible computed|visible arithmetic mean|复算|表中写|不是|delta|差值)",
    re.IGNORECASE,
)
NUMERIC_TEXT_TAGS = {"p", "li", "td", "th", "article", "section"}

LEGACY_SPLIT_NOTE_SECTIONS = {
    "top-priorities",
    "section-review",
    "paragraph-surgery",
    "margin-notes",
    "keep-notes",
}
FORBIDDEN_WORKBENCH_SECTIONS = LEGACY_WORKBENCH_SECTIONS - PAPER_READER_GLOBAL_SECTIONS

PAPER_HTML_SOURCES = {"latexml", "ar5iv", "pandoc", "extracted-text", "manual-fixture"}
DELIVERABLE_PAPER_HTML_SOURCES = {"latexml", "ar5iv", "pandoc", "extracted-text"}
SOURCE_FIDELITY_VALUES = {"deterministic", "limited-scope", "fixture"}
FORBIDDEN_PAPER_READER_CARD_LABELS = {"位置", "原句/片段", "证据/验证"}
MECHANICAL_CARD_PROVENANCE_RE = re.compile(
    r"(data-sentence-id|data-paragraph-id|source-derived paper-reader|generated by render_paper_html\.py|"
    r"sentence span generated|paragraph id generated|heading id generated|section-paragraph-sentence)",
    re.IGNORECASE,
)
MEANINGFUL_CARD_EVIDENCE_RE = re.compile(
    r"(table|figure|caption|pdf|page|computed|recomputed|reported|visible|reference|citation|bib|checklist|"
    r"source line|human|audit|表|图|页|复算|差值|引用|文献|清单|源码|人工|审计)",
    re.IGNORECASE,
)
HASH_RE = re.compile(r"^(sha1|sha256):([0-9a-fA-F]{8,})$")
ANNOTATION_ONLY_CLASSES = {
    "has-annotation",
    "has-sentence-annotation",
    "has-paragraph-annotation",
    "has-section-annotation",
    "has-paper-annotation",
    "is-active",
    "paper-paragraph",
}
ANNOTATION_ONLY_ATTRS = {
    "aria-describedby",
    "onclick",
    "onkeydown",
    "role",
    "tabindex",
}
def compact_text(value: object) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


class StrippedTextParser(HTMLParser):
    def __init__(self, *, final_html: bool) -> None:
        super().__init__()
        self.final_html = final_html
        self.parts: list[str] = []
        self.body_depth = 0
        self.paper_pane_depth = 0
        self.skip_depth = 0
        self.stack: list[tuple[bool, bool, bool]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr = {key: value or "" for key, value in attrs}
        class_names = attr.get("class", "").split()
        starts_body = tag == "body"
        starts_paper_pane = self.final_html and "paper-pane" in class_names
        include_context = self.paper_pane_depth > 0 if self.final_html else (self.body_depth > 0 or tag == "body")
        starts_skip = include_context and (
            tag in {"script", "style"}
            or attr.get("id") in {"annotation-panel", "paper-overview-annotations"}
            or bool({"annotation-card", "annotation-bubble"} & set(class_names))
        )
        if starts_body:
            self.body_depth += 1
        if starts_paper_pane:
            self.paper_pane_depth += 1
        elif self.paper_pane_depth > 0:
            self.paper_pane_depth += 1
        if starts_skip:
            self.skip_depth += 1
        elif self.skip_depth > 0:
            self.skip_depth += 1
        self.stack.append((starts_body, self.paper_pane_depth > 0, self.skip_depth > 0))

    def handle_endtag(self, tag: str) -> None:
        if not self.stack:
            return
        starts_body, in_paper_pane, in_skip = self.stack.pop()
        if in_skip and self.skip_depth > 0:
            self.skip_depth -= 1
        if in_paper_pane and self.paper_pane_depth > 0:
            self.paper_pane_depth -= 1
        if starts_body and self.body_depth > 0:
            self.body_depth -= 1

    def handle_data(self, data: str) -> None:
        include_context = self.paper_pane_depth > 0 if self.final_html else self.body_depth > 0 or not self.stack
        if include_context and self.skip_depth == 0:
            self.parts.append(data)


class PaperReaderCardCopyParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.stack: list[dict[str, bool]] = []
        self.paper_reader_depth = 0
        self.annotation_panel_depth = 0
        self.card_depth = 0
        self.label_depth = 0
        self.current_card: dict[str, object] | None = None
        self.current_label_parts: list[str] = []
        self.cards: list[dict[str, object]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr = {key: value or "" for key, value in attrs}
        class_names = attr.get("class", "").split()
        starts_paper_reader = attr.get("id") == "paper-reader"
        starts_annotation_panel = self.paper_reader_depth > 0 and attr.get("id") == "annotation-panel"
        starts_card = self.annotation_panel_depth > 0 and "annotation-card" in class_names
        starts_label = self.card_depth > 0 and tag in {"dt", "strong", "b", "th"}
        if starts_paper_reader:
            self.paper_reader_depth += 1
        elif self.paper_reader_depth > 0:
            self.paper_reader_depth += 1
        if starts_annotation_panel:
            self.annotation_panel_depth += 1
        elif self.annotation_panel_depth > 0:
            self.annotation_panel_depth += 1
        if starts_card:
            self.card_depth += 1
            self.current_card = {
                "id": attr.get("id") or attr.get("data-issue-ids") or "<unknown annotation card>",
                "text_parts": [],
                "labels": [],
            }
        elif self.card_depth > 0:
            self.card_depth += 1
        if starts_label:
            self.label_depth += 1
            self.current_label_parts = []
        elif self.label_depth > 0:
            self.label_depth += 1
        self.stack.append(
            {
                "paper_reader": self.paper_reader_depth > 0,
                "annotation_panel": self.annotation_panel_depth > 0,
                "card": self.card_depth > 0,
                "label": self.label_depth > 0,
                "starts_card": starts_card,
            }
        )

    def handle_endtag(self, tag: str) -> None:
        if not self.stack:
            return
        state = self.stack.pop()
        if state.get("label") and self.label_depth == 1 and self.current_card is not None:
            labels = self.current_card.get("labels")
            if isinstance(labels, list):
                labels.append(compact_text("".join(self.current_label_parts)).rstrip("：:"))
            self.current_label_parts = []
        if state.get("label") and self.label_depth > 0:
            self.label_depth -= 1
        if state.get("starts_card") and self.current_card is not None:
            self.cards.append(self.current_card)
            self.current_card = None
        if state.get("card") and self.card_depth > 0:
            self.card_depth -= 1
        if state.get("annotation_panel") and self.annotation_panel_depth > 0:
            self.annotation_panel_depth -= 1
        if state.get("paper_reader") and self.paper_reader_depth > 0:
            self.paper_reader_depth -= 1

    def handle_data(self, data: str) -> None:
        if self.current_card is not None:
            parts = self.current_card.get("text_parts")
            if isinstance(parts, list):
                parts.append(data)
        if self.label_depth > 0:
            self.current_label_parts.append(data)


def parse_declared_hash(value: str) -> tuple[str, str] | None:
    match = HASH_RE.fullmatch(value.strip())
    if not match:
        return None
    return match.group(1), match.group(2).lower()


def digest_path(path: Path, algorithm: str) -> str:
    digest = hashlib.new(algorithm)
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_source_hash(source_path: Path, declared_hash: str, label: str) -> list[str]:
    parsed = parse_declared_hash(declared_hash)
    if parsed is None:
        return [f"{label} source hash must look like sha1:<hex> or sha256:<hex>"]
    algorithm, expected = parsed
    actual = digest_path(source_path, algorithm)
    if actual != expected:
        return [f"{label} source hash mismatch: declared {algorithm}:{expected}, computed {algorithm}:{actual}"]
    return []


def annotation_stripped_text(html_text: str, *, final_html: bool) -> str:
    if BeautifulSoup is None:
        parser = StrippedTextParser(final_html=final_html)
        parser.feed(html_text)
        return compact_text(" ".join(parser.parts))
    soup = BeautifulSoup(html_text, "html.parser")
    root = soup.select_one(".paper-pane") if final_html else None
    if root is None:
        root = soup.body or soup
    for selector in (
        "script",
        "style",
        "#annotation-panel",
        ".annotation-card",
        ".annotation-bubble",
        "#paper-overview-annotations",
    ):
        for node in list(root.select(selector)):
            node.decompose()
    for tag in root.find_all(True):
        for attr in list(tag.attrs):
            if attr.startswith("data-") or attr in ANNOTATION_ONLY_ATTRS:
                del tag.attrs[attr]
        classes = tag.get("class", [])
        if isinstance(classes, str):
            classes = classes.split()
        if classes:
            kept = [class_name for class_name in classes if class_name not in ANNOTATION_ONLY_CLASSES]
            if kept:
                tag["class"] = kept
            elif "class" in tag.attrs:
                del tag.attrs["class"]
    return compact_text(root.get_text(" ", strip=True))


def source_integrity_tokens(text: str) -> Counter[str]:
    return Counter(re.findall(r"[A-Za-z0-9]+|[\u4e00-\u9fff]", text.lower()))


def audit_source_integrity(html_path: Path, parser: AriadneHTMLParser, source_path: Path | None = None) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    if not parser.paper_panes:
        return errors, warnings
    needs_source = [
        pane for pane in parser.paper_panes if pane.get("source") in DELIVERABLE_PAPER_HTML_SOURCES and pane.get("fidelity") != "fixture"
    ]
    if source_path is None:
        if needs_source:
            warnings.append("#paper-reader source integrity comparison skipped; pass --source with the pre-annotation source artifact")
        return errors, warnings
    if not source_path.exists():
        return [f"#paper-reader source artifact does not exist: {source_path}"], warnings

    source_text = source_path.read_text(encoding="utf-8")
    rendered_text = html_path.read_text(encoding="utf-8")
    source_body = annotation_stripped_text(source_text, final_html=False)
    rendered_body = annotation_stripped_text(rendered_text, final_html=True)
    if source_body != rendered_body:
        if source_integrity_tokens(source_body) != source_integrity_tokens(rendered_body):
            errors.append("#paper-reader body differs from source artifact after stripping annotation-only markup")
        else:
            warnings.append("#paper-reader source text is complete but reordered by paged/floating layout")

    for idx, pane in enumerate(parser.paper_panes, 1):
        declared_hash = pane.get("hash", "")
        if declared_hash:
            errors.extend(validate_source_hash(source_path, declared_hash, f"#paper-reader .paper-pane #{idx}"))
    return errors, warnings


def audit_paper_reader_card_copy(html_text: str) -> list[str]:
    if BeautifulSoup is None:
        parser = PaperReaderCardCopyParser()
        parser.feed(html_text)
        errors: list[str] = []
        for card in parser.cards:
            card_id = str(card.get("id") or "<unknown annotation card>")
            labels = [str(label) for label in card.get("labels", []) if str(label)]
            for label in labels:
                if label in FORBIDDEN_PAPER_READER_CARD_LABELS:
                    errors.append(
                        f"paper-reader annotation card `{card_id}` must not show visible `{label}`; "
                        "the active paper anchor already supplies location/source text"
                    )
            text = compact_text(" ".join(str(part) for part in card.get("text_parts", [])))
            if MECHANICAL_CARD_PROVENANCE_RE.search(text):
                errors.append(f"paper-reader annotation card `{card_id}` exposes mechanical renderer provenance")
            if "核查依据" in labels and not MEANINGFUL_CARD_EVIDENCE_RE.search(text):
                errors.append(
                    f"paper-reader annotation card `{card_id}` shows `核查依据` without concrete manuscript-level evidence"
                )
        return errors
    soup = BeautifulSoup(html_text, "html.parser")
    errors: list[str] = []
    for card in soup.select("#paper-reader #annotation-panel .annotation-card"):
        card_id = card.get("id") or card.get("data-issue-ids") or "<unknown annotation card>"
        label_nodes = card.find_all(["dt", "strong", "b", "th"])
        for node in label_nodes:
            label = compact_text(node.get_text(" ", strip=True)).rstrip("：:")
            if label in FORBIDDEN_PAPER_READER_CARD_LABELS:
                errors.append(
                    f"paper-reader annotation card `{card_id}` must not show visible `{label}`; "
                    "the active paper anchor already supplies location/source text"
                )
        text = compact_text(card.get_text(" ", strip=True))
        if MECHANICAL_CARD_PROVENANCE_RE.search(text):
            errors.append(f"paper-reader annotation card `{card_id}` exposes mechanical renderer provenance")
        evidence_label_nodes = [node for node in label_nodes if compact_text(node.get_text(" ", strip=True)).rstrip("：:") == "核查依据"]
        if evidence_label_nodes and not MEANINGFUL_CARD_EVIDENCE_RE.search(text):
            errors.append(
                f"paper-reader annotation card `{card_id}` shows `核查依据` without concrete manuscript-level evidence"
            )
    return errors


class AriadneHTMLParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.ids: set[str] = set()
        self.report_kind = ""
        self.href_anchors: set[str] = set()
        self.section_stack: list[str] = []
        self.counts = {
            "margin_rows": 0,
            "surgery_rows": 0,
            "section_review_rows": 0,
            "pdf_pages": 0,
            "severity_items": 0,
        }
        self.text_stack: list[tuple[str, list[str]]] = []
        self.current_text_parts: list[str] = []
        self.numeric_texts: list[str] = []
        self.defined_finding_ids: set[str] = set()
        self.linked_finding_refs: list[tuple[str, str]] = []
        self.raw_schema_key_texts: list[str] = []
        self.tables: list[dict[str, object]] = []
        self.table_stack: list[dict[str, object]] = []
        self.section_text_stack: list[tuple[str, list[str]]] = []
        self.section_texts: dict[str, str] = {}
        self.issue_item_stack: list[dict[str, str | list[str]]] = []
        self.issue_items: list[dict[str, str]] = []
        self.paper_sentence_ids: set[str] = set()
        self.paper_paragraph_ids: set[str] = set()
        self.paper_section_ids: set[str] = set()
        self.paper_overview_ids: set[str] = set()
        self.issue_sentences: list[dict[str, str]] = []
        self.issue_anchors: list[dict[str, str]] = []
        self.annotation_targets: set[tuple[str, str]] = set()
        self.annotation_cards: list[dict[str, str]] = []
        self.unanchored_annotation_cards: list[dict[str, str]] = []
        self.annotation_issue_refs: list[tuple[str, str]] = []
        self.issue_sentence_refs: list[tuple[str, str]] = []
        self.paper_panes: list[dict[str, str]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr = {key: value or "" for key, value in attrs}
        element_id = attr.get("id")
        class_names = attr.get("class", "").split()
        if "review-report" in class_names and attr.get("data-report-kind"):
            self.report_kind = attr.get("data-report-kind", "")
        if element_id:
            self.ids.add(element_id)
        href = attr.get("href", "")
        if href.startswith("#") and len(href) > 1:
            self.href_anchors.add(href[1:])

        if tag == "section":
            self.section_stack.append(element_id or "")
            self.section_text_stack.append((element_id or "", []))
            if "pdf-anchor" in attr.get("class", "").split():
                self.counts["pdf_pages"] += 1
        elif tag == "tr":
            note_kind = attr.get("data-note-kind", "")
            if "deep-reading-notes" in self.section_stack:
                if note_kind == "sentence" and "data-severity" in attr:
                    self.counts["margin_rows"] += 1
                if note_kind == "paragraph" and ("data-decision" in attr or "data-severity" in attr):
                    self.counts["surgery_rows"] += 1
                if note_kind == "section" and "data-severity" in attr:
                    self.counts["section_review_rows"] += 1
        elif tag == "article":
            note_kind = attr.get("data-note-kind", "")
            if "deep-reading-notes" in self.section_stack:
                if note_kind == "sentence":
                    self.counts["margin_rows"] += 1
                if note_kind == "paragraph":
                    self.counts["surgery_rows"] += 1
                if note_kind == "section":
                    self.counts["section_review_rows"] += 1

        if "paper-reader" in self.section_stack:
            if "paper-pane" in class_names:
                self.paper_panes.append(
                    {
                        "source": attr.get("data-paper-html-source", ""),
                        "fidelity": attr.get("data-source-fidelity", ""),
                        "artifact": attr.get("data-source-artifact", ""),
                        "hash": attr.get("data-source-hash", ""),
                        "sentence_id_scheme": attr.get("data-sentence-id-scheme", ""),
                        "annotation_mode": attr.get("data-annotation-mode", ""),
                        "visible_scope": attr.get("data-visible-scope", ""),
                    }
                )
            sentence_id = attr.get("data-sentence-id", "")
            is_paper_sentence = "paper-sentence" in class_names
            is_issue_sentence = (
                is_paper_sentence
                and (
                    "has-annotation" in class_names
                    or attr.get("data-has-issue") == "true"
                    or bool(attr.get("data-issue-ids"))
                )
            )
            if is_paper_sentence:
                if sentence_id:
                    self.paper_sentence_ids.add(sentence_id)
                if is_issue_sentence:
                    issue_ids = attr.get("data-issue-ids", "")
                    self.issue_sentences.append(
                        {
                            "sentence_id": sentence_id,
                            "severity": attr.get("data-severity", ""),
                            "issue_type": attr.get("data-issue-type", ""),
                            "issue_ids": issue_ids,
                            "data_has_issue": attr.get("data-has-issue", ""),
                            "aria_describedby": attr.get("aria-describedby", ""),
                            "tag": tag,
                        }
                    )
                    for ref in re.findall(r"F\d+[A-Za-z]?", issue_ids):
                        self.issue_sentence_refs.append((ref, sentence_id or "<missing sentence id>"))
            paragraph_id = attr.get("data-paragraph-id", "")
            if paragraph_id:
                self.paper_paragraph_ids.add(paragraph_id)
            if element_id:
                self.paper_section_ids.add(element_id)
            if element_id == "paper-overview-annotations":
                self.paper_overview_ids.add("paper")
            paper_button_id = attr.get("data-paper-id", "")
            if paper_button_id and "annotation-bubble" in class_names and "paper" in class_names:
                self.paper_overview_ids.add(paper_button_id)
            for level, target_id, marker_class in (
                ("paragraph", paragraph_id, "has-paragraph-annotation"),
                ("section", element_id or "", "has-section-annotation"),
                ("paper", paper_button_id if "annotation-bubble" in class_names and "paper" in class_names else "", "has-paper-annotation"),
            ):
                if target_id and marker_class in class_names:
                    issue_ids = attr.get("data-issue-ids", "")
                    self.issue_anchors.append(
                        {
                            "level": level,
                            "target": target_id,
                            "severity": attr.get("data-severity", ""),
                            "issue_type": attr.get("data-issue-type", ""),
                            "issue_ids": issue_ids,
                            "data_has_issue": attr.get("data-has-issue", ""),
                        }
                    )
                    for ref in re.findall(r"F\d+[A-Za-z]?", issue_ids):
                        self.issue_sentence_refs.append((ref, target_id))
            is_annotation_card = "annotation-card" in class_names
            is_unanchored_annotation = is_annotation_card and attr.get("data-unanchored") == "true"
            target_sentence = attr.get("data-target-sentence", "")
            target_level = attr.get("data-target-level", "sentence" if target_sentence else "")
            target_paragraph = attr.get("data-target-paragraph", "")
            target_section = attr.get("data-target-section", "")
            target_paper = attr.get("data-target-paper", "")
            if is_unanchored_annotation:
                issue_ids = attr.get("data-issue-ids", "")
                self.unanchored_annotation_cards.append(
                    {
                        "target_level": target_level,
                        "target_sentence": target_sentence,
                        "target_paragraph": target_paragraph,
                        "target_section": target_section,
                        "target_paper": target_paper,
                        "severity": attr.get("data-severity", ""),
                        "issue_type": attr.get("data-issue-type", ""),
                        "issue_ids": issue_ids,
                    }
                )
            target_by_level = {
                "sentence": target_sentence,
                "paragraph": target_paragraph,
                "section": target_section,
                "paper": target_paper,
            }
            target_value = target_by_level.get(target_level, "")
            if target_value:
                issue_ids = attr.get("data-issue-ids", "")
                self.annotation_targets.add((target_level, target_value))
                self.annotation_cards.append(
                    {
                        "target_level": target_level,
                        "target_sentence": target_sentence,
                        "target_paragraph": target_paragraph,
                        "target_section": target_section,
                        "target_paper": target_paper,
                        "severity": attr.get("data-severity", ""),
                        "issue_type": attr.get("data-issue-type", ""),
                        "issue_ids": issue_ids,
                    }
                )
                for ref in re.findall(r"F\d+[A-Za-z]?", issue_ids):
                    self.annotation_issue_refs.append((ref, target_value))

        if "data-severity" in attr:
            self.counts["severity_items"] += 1
            if attr.get("data-issue-type"):
                self.issue_item_stack.append(
                    {
                        "severity": attr.get("data-severity", ""),
                        "issue_type": attr.get("data-issue-type", ""),
                        "tag": tag,
                        "text_parts": [],
                    }
                )
        if tag == "table":
            self.table_stack.append(
                {
                    "has_caption": False,
                    "header_without_scope": 0,
                    "id": element_id or "",
                    "in_paper_reader": "paper-reader" in self.section_stack,
                }
            )
        elif tag == "caption" and self.table_stack:
            self.table_stack[-1]["has_caption"] = True
        elif tag == "th" and self.table_stack:
            if "scope" not in attr:
                self.table_stack[-1]["header_without_scope"] = int(self.table_stack[-1]["header_without_scope"]) + 1
        if element_id and re.fullmatch(r"F\d+[A-Za-z]?", element_id):
            self.defined_finding_ids.add(element_id)
        if tag == "a":
            text_ref = attr.get("href", "")
            if text_ref.startswith("#") and re.fullmatch(r"#F\d+[A-Za-z]?", text_ref):
                self.linked_finding_refs.append((text_ref[1:], text_ref))
        if tag in NUMERIC_TEXT_TAGS:
            self.text_stack.append((tag, []))

    def handle_endtag(self, tag: str) -> None:
        if tag in NUMERIC_TEXT_TAGS and self.text_stack and self.text_stack[-1][0] == tag:
            _, parts = self.text_stack.pop()
            text = "".join(parts).strip()
            if NUMERIC_CONTEXT_RE.search(text):
                self.numeric_texts.append(re.sub(r"\s+", " ", text))
            if re.search(r"\b(reported_value|visible_computed_value|aggregation_caveat)\b", text):
                self.raw_schema_key_texts.append(re.sub(r"\s+", " ", text))
            if self.text_stack and text:
                self.text_stack[-1][1].append(" " + text)
        if tag == "section" and self.section_stack and self.section_stack[-1] == (self.section_text_stack[-1][0] if self.section_text_stack else ""):
            section_id, parts = self.section_text_stack.pop() if self.section_text_stack else ("", [])
            if section_id:
                section_text = re.sub(r"\s+", " ", "".join(parts)).strip()
                self.section_texts[section_id] = section_text
            if self.section_text_stack and parts:
                self.section_text_stack[-1][1].append(" ".join(parts))
            self.section_stack.pop()
        if tag == "table" and self.table_stack:
            self.tables.append(self.table_stack.pop())
        if self.issue_item_stack and tag == self.issue_item_stack[-1].get("tag"):
            item = self.issue_item_stack.pop()
            parts = item.get("text_parts", [])
            text = re.sub(r"\s+", " ", "".join(parts if isinstance(parts, list) else [])).strip()
            self.issue_items.append(
                {
                    "severity": str(item.get("severity", "")),
                    "issue_type": str(item.get("issue_type", "")),
                    "text": text,
                }
            )

    def handle_data(self, data: str) -> None:
        if self.text_stack:
            self.text_stack[-1][1].append(data)
        if self.section_text_stack:
            self.section_text_stack[-1][1].append(data)
        for item in self.issue_item_stack:
            parts = item.get("text_parts")
            if isinstance(parts, list):
                parts.append(data)


def find_declared_count(text: str, labels: list[str]) -> int | None:
    for label in labels:
        pattern = rf"<td>\s*{re.escape(label)}\s*</td>\s*<td>\s*(\d+)\s*</td>"
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return int(match.group(1))
    return None


def audit(path: Path) -> tuple[list[str], list[str]]:
    text = path.read_text(encoding="utf-8")
    parser = AriadneHTMLParser()
    parser.feed(text)

    errors: list[str] = []
    warnings: list[str] = []
    report_kind = parser.report_kind
    is_current_paper_reader = report_kind in REQUIRED_SECTIONS_BY_KIND
    required_sections = REQUIRED_SECTIONS_BY_KIND.get(report_kind, LEGACY_WORKBENCH_SECTIONS)
    missing_sections = sorted(required_sections - parser.ids)
    for section_id in missing_sections:
        errors.append(f"missing required section #{section_id}")

    if is_current_paper_reader:
        forbidden_workbench = sorted(FORBIDDEN_WORKBENCH_SECTIONS & parser.ids)
        if forbidden_workbench:
            errors.append(
                "paper-reader reports must not render legacy workbench sections: "
                + ", ".join(f"#{section_id}" for section_id in forbidden_workbench)
            )

    if "paper-reader" in parser.ids:
        if "annotation-panel" not in parser.ids:
            errors.append("#paper-reader is missing #annotation-panel")
        if not parser.paper_panes:
            errors.append("#paper-reader is missing a `.paper-pane` with source provenance metadata")
        for idx, pane in enumerate(parser.paper_panes, 1):
            source = pane.get("source", "")
            fidelity = pane.get("fidelity", "")
            prefix = f"#paper-reader .paper-pane #{idx}"
            if source not in PAPER_HTML_SOURCES:
                errors.append(f"{prefix} has invalid or missing data-paper-html-source `{source}`")
            if source not in DELIVERABLE_PAPER_HTML_SOURCES and source != "manual-fixture":
                errors.append(f"{prefix} uses non-deliverable paper HTML source `{source}`")
            if fidelity not in SOURCE_FIDELITY_VALUES:
                errors.append(f"{prefix} has invalid or missing data-source-fidelity `{fidelity}`")
            if source == "manual-fixture" and fidelity != "fixture":
                errors.append(f"{prefix} manual-fixture source must use data-source-fidelity=\"fixture\"")
            if source in DELIVERABLE_PAPER_HTML_SOURCES and fidelity == "fixture":
                errors.append(f"{prefix} deliverable source `{source}` cannot use fixture fidelity")
            for field, attr_name in (
                ("artifact", "data-source-artifact"),
                ("hash", "data-source-hash"),
                ("sentence_id_scheme", "data-sentence-id-scheme"),
                ("annotation_mode", "data-annotation-mode"),
            ):
                if not pane.get(field):
                    errors.append(f"{prefix} is missing `{attr_name}`")
            if pane.get("annotation_mode") and pane.get("annotation_mode") != "overlay-only":
                errors.append(f"{prefix} must use data-annotation-mode=\"overlay-only\"")
            if pane.get("hash") and parse_declared_hash(pane["hash"]) is None:
                errors.append(f"{prefix} data-source-hash must look like sha1:<hex> or sha256:<hex>")
            if fidelity == "limited-scope" and not pane.get("visible_scope"):
                errors.append(f"{prefix} limited-scope paper reader must set `data-visible-scope`")
        if not parser.issue_sentences and not parser.issue_anchors:
            errors.append("#paper-reader has no annotated issue anchors (`.paper-sentence.has-annotation`, paragraph/section bubble, or paper overview)")
        if not parser.annotation_cards:
            errors.append("#paper-reader has no annotation cards (`data-target-*`)")
        for item in parser.issue_sentences:
            sentence_id = item.get("sentence_id", "")
            if not sentence_id:
                errors.append("annotated paper sentence is missing `data-sentence-id`")
                continue
            if item.get("data_has_issue") != "true":
                errors.append(f"annotated paper sentence `{sentence_id}` must set data-has-issue=\"true\"")
            for field, attr_name in (
                ("severity", "data-severity"),
                ("issue_type", "data-issue-type"),
                ("issue_ids", "data-issue-ids"),
            ):
                if not item.get(field):
                    errors.append(f"annotated paper sentence `{sentence_id}` is missing `{attr_name}`")
            if ("sentence", sentence_id) not in parser.annotation_targets:
                errors.append(f"annotated paper sentence `{sentence_id}` has no matching annotation card")
        for item in parser.issue_anchors:
            level = item.get("level", "")
            target = item.get("target", "")
            if not target:
                errors.append(f"annotated {level} anchor is missing a target id")
                continue
            if item.get("data_has_issue") != "true":
                errors.append(f"annotated {level} anchor `{target}` must set data-has-issue=\"true\"")
            for field, attr_name in (
                ("severity", "data-severity"),
                ("issue_type", "data-issue-type"),
                ("issue_ids", "data-issue-ids"),
            ):
                if not item.get(field):
                    errors.append(f"annotated {level} anchor `{target}` is missing `{attr_name}`")
            if (level, target) not in parser.annotation_targets:
                errors.append(f"annotated {level} anchor `{target}` has no matching annotation card")
        for item in parser.annotation_cards:
            level = item.get("target_level", "sentence")
            target = (
                item.get("target_sentence", "")
                or item.get("target_paragraph", "")
                or item.get("target_section", "")
                or item.get("target_paper", "")
            )
            if level == "sentence" and target and target not in parser.paper_sentence_ids:
                errors.append(f"annotation card targets unknown paper sentence `{target}`")
            if level == "paragraph" and target and target not in parser.paper_paragraph_ids:
                errors.append(f"annotation card targets unknown paper paragraph `{target}`")
            if level == "section" and target and target not in parser.paper_section_ids:
                errors.append(f"annotation card targets unknown paper section `{target}`")
            if level == "paper" and target and target not in parser.paper_overview_ids:
                errors.append(f"annotation card targets missing paper overview `{target}`")
            for field, attr_name in (
                ("severity", "data-severity"),
                ("issue_type", "data-issue-type"),
                ("issue_ids", "data-issue-ids"),
            ):
                if not item.get(field):
                    errors.append(f"annotation card for `{target}` is missing `{attr_name}`")
        for item in parser.unanchored_annotation_cards:
            for key in ("target_sentence", "target_paragraph", "target_section", "target_paper"):
                target = item.get(key, "")
                if target:
                    errors.append(f"unanchored annotation card must not set {key.replace('_', '-')} `{target}`")
            for field, attr_name in (
                ("severity", "data-severity"),
                ("issue_type", "data-issue-type"),
                ("issue_ids", "data-issue-ids"),
            ):
                if not item.get(field):
                    errors.append(f"unanchored annotation card is missing `{attr_name}`")
        errors.extend(audit_paper_reader_card_copy(text))

    if parser.section_stack or parser.issue_item_stack or parser.text_stack or parser.table_stack:
        errors.append("HTML appears structurally incomplete or misnested; parser stacks were not fully closed")

    for anchor in sorted(parser.href_anchors):
        if anchor not in parser.ids:
            errors.append(f"nav/link target #{anchor} has no matching element id")

    if not is_current_paper_reader:
        if parser.counts["margin_rows"] == 0:
            errors.append("#deep-reading-notes has no sentence rows (`data-note-kind=\"sentence\"`)")
        if parser.counts["surgery_rows"] == 0:
            errors.append("#deep-reading-notes has no paragraph rows (`data-note-kind=\"paragraph\"`)")
        if parser.counts["section_review_rows"] == 0:
            errors.append("#deep-reading-notes has no section reflection rows (`data-note-kind=\"section\"`)")
        legacy = sorted(LEGACY_SPLIT_NOTE_SECTIONS & parser.ids)
        if legacy or "section-comments" in parser.ids or "section-reflections" in parser.ids:
            errors.append(
                "use ordered #deep-reading-notes instead of separate/repeated sections: "
                + ", ".join(legacy + [item for item in ("section-comments", "section-reflections") if item in parser.ids])
            )

    if not is_current_paper_reader:
        declared_margin = find_declared_count(
            text,
            [
                "Visible sentence issue notes",
                "Visible sentence notes",
                "Visible sentence-like issue rows",
                "Sentence notes",
                "句子级批注",
                "Margin notes",
                "逐句批注",
            ],
        )
        if declared_margin is not None and declared_margin != parser.counts["margin_rows"]:
            errors.append(
                f"declared sentence/margin-note count {declared_margin} != body count {parser.counts['margin_rows']}"
            )

        declared_surgery = find_declared_count(
            text,
            [
                "Visible paragraph issue rows",
                "Visible paragraph rows",
                "Paragraph rows",
                "Paragraph surgery rows",
                "逐段手术",
                "Paragraph surgery",
                "段落级批注",
            ],
        )
        if declared_surgery is not None and declared_surgery != parser.counts["surgery_rows"]:
            errors.append(f"declared paragraph row count {declared_surgery} != body count {parser.counts['surgery_rows']}")

        declared_section_reflections = find_declared_count(
            text,
            [
                "Section reflection rows",
                "章节读后反思",
                "章节反思",
            ],
        )
        if declared_section_reflections is not None and declared_section_reflections != parser.counts["section_review_rows"]:
            errors.append(
                f"declared section-reflection count {declared_section_reflections} != body count {parser.counts['section_review_rows']}"
            )

    if "Coverage consistency" not in text and "coverage consistency" not in text:
        warnings.append("coverage receipt does not mention Coverage consistency gate")
    if "pending in" in text and "Pending in" not in text:
        warnings.append("pending units are mentioned outside the standard Pending in receipt column")
    if not is_current_paper_reader:
        issue_index_text = parser.section_texts.get("issue-index", "")
        if "降级条件" in issue_index_text or "下一稿任务" in issue_index_text:
            errors.append("#issue-index should be compact; move 降级条件/下一稿任务 to findings.json, deep-reading rows, or Revision Plan")

    for numeric_text in parser.numeric_texts:
        if not VAGUE_NUMERIC_RE.search(numeric_text):
            continue
        numbers = NUMERIC_VALUE_RE.findall(numeric_text)
        has_concrete_cue = bool(CONCRETE_NUMERIC_CUE_RE.search(numeric_text))
        if len(numbers) < 2 or not has_concrete_cue:
            preview = numeric_text[:240]
            errors.append(
                "vague numeric language without concrete reported/computed/delta values: "
                f"{preview!r}"
            )

    for raw_text in parser.raw_schema_key_texts:
        preview = raw_text[:240]
        errors.append(
            "Chinese-facing HTML body renders raw numerical schema keys; use 表中数值 / 可见复算值 / 差值 / 口径说明: "
            f"{preview!r}"
        )

    for ref, source in parser.linked_finding_refs:
        if ref not in parser.defined_finding_ids:
            errors.append(f"linked finding `{ref}` has no matching finding/id anchor")
    if report_kind != "paper-reader-only":
        for ref, source in parser.issue_sentence_refs:
            if ref not in parser.defined_finding_ids:
                errors.append(f"paper sentence `{source}` references finding `{ref}` with no matching finding/id anchor")
        for ref, target in parser.annotation_issue_refs:
            if ref not in parser.defined_finding_ids:
                errors.append(f"annotation card for `{target}` references finding `{ref}` with no matching finding/id anchor")

    for table in parser.tables:
        if table.get("in_paper_reader"):
            continue
        if not table.get("has_caption"):
            errors.append("table is missing <caption>")
        if int(table.get("header_without_scope", 0)) > 0:
            errors.append("table has <th> without scope attribute")

    return errors, warnings


def audit_with_source(path: Path, source_path: Path | None = None) -> tuple[list[str], list[str]]:
    errors, warnings = audit(path)
    parser = AriadneHTMLParser()
    parser.feed(path.read_text(encoding="utf-8"))
    integrity_errors, integrity_warnings = audit_source_integrity(path, parser, source_path)
    errors.extend(integrity_errors)
    warnings.extend(integrity_warnings)
    return errors, warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("html", type=Path)
    parser.add_argument("--source", type=Path, help="Pre-annotation paper-reader source artifact to hash and compare")
    args = parser.parse_args(argv)

    errors, warnings = audit_with_source(args.html, args.source)
    for warning in warnings:
        print(f"WARNING: {warning}")
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    if errors:
        return 1
    print("Ariadne HTML report audit passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
